//
// Created by sercan.ersoy on 24.07.2019.
//

#ifndef DATABASE_MANAGEMENT_SYSTEM_CONSTANTS_H
#define DATABASE_MANAGEMENT_SYSTEM_CONSTANTS_H

#define SYS_CAT_HEADER_SIZE 2
#define SYS_CAT_PAGE_HEADER_SIZE 2
#define SYS_CAT_TYPE_HEADER_SIZE 12
#define SYS_CAT_TYPE_LIMIT 10
#define SYS_CAT_PAGE_LIMIT 50
#define SYS_CAT_TYPE_FIELD_SIZE 10
#define SYS_CAT_TYPE_FIELD_LIMIT 10
#define SYS_CAT_TYPE_SIZE (SYS_CAT_TYPE_FIELD_SIZE*SYS_CAT_TYPE_FIELD_LIMIT+SYS_CAT_TYPE_HEADER_SIZE)
#define SYS_CAT_PAGE_SIZE (SYS_CAT_TYPE_SIZE*SYS_CAT_TYPE_LIMIT+SYS_CAT_PAGE_HEADER_SIZE)

#define DATA_FILE_HEADER_SIZE 2
#define DATA_FILE_PAGE_HEADER_SIZE 2
#define DATA_FILE_RECORD_HEADER_SIZE 1
#define DATA_FILE_RECORD_LIMIT 30
#define DATA_FILE_PAGE_LIMIT 50
#define DATA_FILE_RECORD_FIELD_SIZE 4
#define DATA_FILE_RECORD_FIELD_LIMIT 10
#define DATA_FILE_RECORD_SIZE (DATA_FILE_RECORD_FIELD_SIZE*DATA_FILE_RECORD_FIELD_LIMIT+DATA_FILE_RECORD_HEADER_SIZE)
#define DATA_FILE_PAGE_SIZE (DATA_FILE_RECORD_SIZE*DATA_FILE_RECORD_LIMIT+DATA_FILE_PAGE_HEADER_SIZE)

#endif //DATABASE_MANAGEMENT_SYSTEM_CONSTANTS_H
