//
// Created by sercanersoy on 25.07.2019.
//

#ifndef DATABASE_MANAGEMENT_SYSTEM_DATAFILERECORDHEADER_H
#define DATABASE_MANAGEMENT_SYSTEM_DATAFILERECORDHEADER_H


class DataFileRecordHeader {
    char valid;
};


#endif //DATABASE_MANAGEMENT_SYSTEM_DATAFILERECORDHEADER_H
